### PR TITLE
Fix crash on empty input.

### LINKED ISSUE #1: If the source length is 0, a fatal error is thrown

### PR DESCRIPTION
**Pull request by calebd**
Fixes #1.

### CODE REVIEW

File: Sources/WagnerFischer.swift [hunk 1]
```diff
@@ -35,6 +35,21 @@ extension EditStep: CustomDebugStringConvertible {
 }
 
 public func editSteps<T>(source: [T], _ destination: [T], compare: (T, T) -> Bool) -> [EditStep<T>] {
+
+    // Return all insertions if the source is empty.
+    if source.isEmpty {
+        return destination.enumerate().map({ index, value in
```
Comment (soffes) [inline Sources/WagnerFischer.swift:41]: Do you want to change this to a range map too?

Comment (calebd) [inline Sources/WagnerFischer.swift:41]: I could. Though we do make use of the value in this case.

Comment (soffes) [inline Sources/WagnerFischer.swift:41]: Oh never mind!
